# Generated by Django 5.2.8 on 2025-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dieta_treinosemana'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='musculos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='treinosemana',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='treinosemana',
            name='musculos',
        ),
        migrations.AddField(
            model_name='treinosemana',
            name='dias',
            field=models.ManyToManyField(to='website.diasemana'),
        ),
        migrations.AddField(
            model_name='treinosemana',
            name='musculos',
            field=models.ManyToManyField(to='website.musculo'),
        ),
    ]
