# Generated by Django 5.2.8 on 2025-11-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_diasemana_musculo_remove_treinosemana_dia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('peso', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='peso atual')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreinoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.diasemana')),
                ('musculos', models.ManyToManyField(to='website.musculo')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='website.semanatreino')),
            ],
        ),
        migrations.DeleteModel(
            name='TreinoSemana',
        ),
    ]
