# Generated by Django 5.2.8 on 2025-11-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_semanatreino_treinodia_delete_treinosemana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinodia',
            name='dia',
        ),
        migrations.DeleteModel(
            name='dieta',
        ),
        migrations.RemoveField(
            model_name='treinodia',
            name='musculos',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.RemoveField(
            model_name='semanatreino',
            name='user',
        ),
        migrations.RemoveField(
            model_name='treinodia',
            name='semana',
        ),
        migrations.DeleteModel(
            name='DiaSemana',
        ),
        migrations.DeleteModel(
            name='Musculo',
        ),
        migrations.DeleteModel(
            name='SemanaTreino',
        ),
        migrations.DeleteModel(
            name='TreinoDia',
        ),
    ]
