# Generated by Django 5.2.8 on 2025-11-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasemana',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='diasemana',
            name='nome',
            field=models.CharField(max_length=13),
        ),
    ]
