# Generated by Django 5.2.8 on 2025-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0002_diasemana_sigla_alter_diasemana_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='musculo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
